### ISSUE TITLE
BugSnag Error - JpaObjectRetrievalFailureException

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-server#648] opened 2023-11-07 10:16 UTC
Potentially caused by the L2 cache

**BugSnag Error**

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/653baa49d5236800099e4fe0?filters[event.since]=all&filters[app.release_stage][]=prod&filters[app.release_stage][]=production&filters[error.status]=open&pivot_tab=event

```
org.springframework.orm.jpa.JpaObjectRetrievalFailureException: Unable to find org.avni.server.domain.Concept with id 189144; nested exception is javax.persistence.EntityNotFoundException: Unable to find org.avni.server.domain.Concept with id 189144
        at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:373)
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:507)
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:153)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy200.findByUuid(Unknown:-1)
        at org.avni.server.service.ObservationService.getObservationContract(ObservationService.java:261)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1723)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.avni.server.service.ObservationService.constructObservations(ObservationService.java:256)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.constructProgramEncounterContractWrapper(ProgramEncounterConstructionService.java:147)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.constructEncountersExcludingSelf(ProgramEncounterConstructionService.java:122)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.constructEnrolments(ProgramEncounterConstructionService.java:173)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.programEnrolmentWrapperForMessageSchedule(ProgramEncounterConstructionService.java:129)
        at org.avni.server.web.request.rules.constructWrappers.RuleServiceEntityContractBuilder.toContract(RuleServiceEntityContractBuilder.java:41)
        at org.avni.server.web.request.rules.constructWrappers.RuleServiceEntityContractBuilder.toContract(RuleServiceEntityContractBuilder.java:59)
        at org.avni.server.service.RuleService.executeMessageRule(RuleService.java:229)
        at org.avni.server.service.RuleService$$FastClassBySpringCGLIB$$ec943409.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
        at org.avni.server.service.RuleService$$EnhancerBySpringCGLIB$$fc884464.executeMessageRule(<generated>:-1)
        at org.avni.messaging.service.IndividualMessagingService.sendAutomatedMessage(IndividualMessagingService.java:48)
        at org.avni.messaging.service.MessagingService.sendMessageToGlific(MessagingService.java:158)
        at org.avni.messaging.service.MessagingService.sendMessage(MessagingService.java:118)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.avni.messaging.service.MessagingService.sendMessages(MessagingService.java:141)
        at org.avni.messaging.service.MessagingService$$FastClassBySpringCGLIB$$a16061e8.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.avni.messaging.service.MessagingService$$EnhancerBySpringCGLIB$$e5ecf161.sendMessages(<generated>:-1)
        at org.avni.messaging.service.MessageSenderJob.sendMessages(MessageSenderJob.java:53)
        at org.avni.messaging.service.MessageSenderJob.sendMessages(MessageSenderJob.java:43)
        at sun.reflect.GeneratedMethodAccessor1818.invoke(Unknown:-1)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

Caused by: javax.persistence.EntityNotFoundException: Unable to find org.avni.server.domain.Concept with id 189144
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:159)
        at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:227)
        at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:278)
        at org.hibernate.event.internal.DefaultLoadEventListener.doOnLoad(DefaultLoadEventListener.java:121)
        at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:89)
        at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1239)
        at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:1122)
        at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:672)
        at org.hibernate.type.ManyToOneType.assemble(ManyToOneType.java:255)
        at org.hibernate.cache.internal.StandardQueryCache.assembleCachedResult(StandardQueryCache.java:208)
        at org.hibernate.cache.internal.StandardQueryCache.get(StandardQueryCache.java:193)
        at org.hibernate.loader.Loader.getResultFromQueryCache(Loader.java:2619)
        at org.hibernate.loader.Loader.listUsingQueryCache(Loader.java:2527)
        at org.hibernate.loader.Loader.list(Loader.java:2499)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:502)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:392)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:216)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1489)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1445)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1414)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1463)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:107)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:214)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:590)
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:578)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy200.findByUuid(Unknown:-1)
        at org.avni.server.service.ObservationService.getObservationContract(ObservationService.java:261)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1723)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.avni.server.service.ObservationService.constructObservations(ObservationService.java:256)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.constructProgramEncounterContractWrapper(ProgramEncounterConstructionService.java:147)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.constructEncountersExcludingSelf(ProgramEncounterConstructionService.java:122)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.constructEnrolments(ProgramEncounterConstructionService.java:173)
        at org.avni.server.web.request.rules.constructWrappers.ProgramEncounterConstructionService.programEnrolmentWrapperForMessageSchedule(ProgramEncounterConstructionService.java:129)
        at org.avni.server.web.request.rules.constructWrappers.RuleServiceEntityContractBuilder.toContract(RuleServiceEntityContractBuilder.java:41)
        at org.avni.server.web.request.rules.constructWrappers.RuleServiceEntityContractBuilder.toContract(RuleServiceEntityContractBuilder.java:59)
        at org.avni.server.service.RuleService.executeMessageRule(RuleService.java:229)
        at org.avni.server.service.RuleService$$FastClassBySpringCGLIB$$ec943409.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:685)
        at org.avni.server.service.RuleService$$EnhancerBySpringCGLIB$$fc884464.executeMessageRule(<generated>:-1)
        at org.avni.messaging.service.IndividualMessagingService.sendAutomatedMessage(IndividualMessagingService.java:48)
        at org.avni.messaging.service.MessagingService.sendMessageToGlific(MessagingService.java:158)
        at org.avni.messaging.service.MessagingService.sendMessage(MessagingService.java:118)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.avni.messaging.service.MessagingService.sendMessages(MessagingService.java:141)
        at org.avni.messaging.service.MessagingService$$FastClassBySpringCGLIB$$a16061e8.invoke(<generated>:-1)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
        at org.avni.messaging.service.MessagingService$$EnhancerBySpringCGLIB$$e5ecf161.sendMessages(<generated>:-1)
        at org.avni.messaging.service.MessageSenderJob.sendMessages(MessageSenderJob.java:53)
        at org.avni.messaging.service.MessageSenderJob.sendMessages(MessageSenderJob.java:43)
        at sun.reflect.GeneratedMethodAccessor1818.invoke(Unknown:-1)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Management of BugSnag error and BugSnag**
https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by 1t5j0y** [comment] 2023-11-08 08:49
Listing some observations to help analyse the cause:

- Seems to be happening only for 'Concept' (even through we are caching other entities as well.
- Happening fairly randomly. Not happening daily. Glific message sending sometimes triggers a bunch of these at the same instant.
- Seems to be occurring for both `findByName` and `findByUuid` usages.
- Stack traces for most occurrences have mention of cache and ManyToOne so it could be some edge case of some related entity not present in the cache while the primary entity is.
```
        at org.hibernate.type.ManyToOneType.assemble(ManyToOneType.java:255)
        at org.hibernate.cache.internal.StandardQueryCache.assembleCachedResult(StandardQueryCache.java:208)
        at org.hibernate.cache.internal.StandardQueryCache.get(StandardQueryCache.java:193)
        at org.hibernate.loader.Loader.getResultFromQueryCache(Loader.java:2619)
```

Continuing to investigate.

**Comment by mahalakshme** [comment] 2023-11-16 06:37
@petmongrels I think for addresslevel and users querying as well we need to add organisation_id in the cache query

**Comment by himeshr** [comment] 2023-11-27 06:33
The fix has been deployed to Avni production as a hotfix by cherrypicking the changes onto 5.1.0 branch.

**Closed** 2023-11-27 07:11 UTC
Labels: bugsnag
