### ISSUE TITLE
Get get sync details should not return subject types, programs, encounter types for which there is no form mapping

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#537] opened 2023-04-16 15:13 UTC
This should include voided and non-voided form mapping. This is required because if get sync details doesn't check for form mapping for then the check for form mapping during the sync for their entities i.e. subject/encounter/enrolment throws no form mapping exception to the user.

One of example of this issue is this:

https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/64263aa022d25c0008da5982

https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by himeshr** [comment] 2023-04-20 09:24
This issue is a duplicate of #528.
https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/528

**Closed by himeshr** 2023-04-20 09:24 UTC
Labels: bug
