### ISSUE TITLE
Bugsnag error

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-server#527] opened 2023-04-10 11:20 UTC
https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-server/errors/642eced1c36a12000856444d

https://avni.readme.io/docs/how-to-use-bugsnag

**Comment by himeshr** [comment] 2023-04-17 05:39
Exception stacktrace for reference:

java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.lang.String
        at org.avni.server.service.IndividualService.lambda$findPhoneNumber$13(IndividualService.java:372)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.HashMap$EntrySpliterator.tryAdvance(HashMap.java:1744)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
        at org.avni.server.service.IndividualService.findPhoneNumber(IndividualService.java:372)
        at org.avni.server.service.IndividualService$$FastClassBySpringCGLIB$$26ae99cc.invoke(<generated>:-1)

**Comment by himeshr** [comment] 2023-04-17 05:40
This is a duplicate of #536 https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/536

**Closed** 2023-04-18 04:16 UTC
Labels: bug
