### ISSUE TITLE
In message rule, date observation evaluates to one day back

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#538] opened 2023-04-17 09:54 UTC
This bug could have got fixed via: https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/874 but need to make sure.

**Steps to reproduce:**
- log into to Lend A Hand India in prod in field app
- register LAHI intern, enrol in Internship LAHI, 
- create LAHI intern attendance program encounter.
- Execute the following say in Program Encounter View for the above created encounter:
let dateTime = this.state.programEncounter.getObservationValue("Date of Attendance");
dateTime = moment(dateTime).format("ll");
console.log(dateTime):
The above prints expected date in client code base.
- But in message rules of LAHI INTERN ATTENDANCE do the same using params.entity.programEncounter:
- It prints one day back.

**Expectation**:
- In message rule as well, the expected(the input) date should get printed in console.
- Check other rules for existence of this issue and fix if necessary.

**Analysis:**
- We are storing date in UTC format, so for date say Apr 30, we store as 2023-04-30T18:30:00.000Z in observations. 

- When printed the observations in message rule:
`("name":"Date of Attendance","datatype":"Date","hiAbsolute":null,"lowAbsolute":null,"keyValues":null,"lowNormal":null,"unit":null},"valueJSON":"{\"value\":\"2023-04-30T18:30:00.000Z\",\"datatype\":\"Date\",\"answer\":\"2023-04-30T00:00:00.000Z\"}"}`

but in Program Encounter View it is:
`{"name":"Date of Attendance","datatype":"Date","uuid":"f90c8c11-caad-4e05-abb0-a28ff8af5799","keyValues":[],"unit":null,"lowAbsolute":null,"lowNormal":null,"answers":[]},"valueJSON":{"value":"2023-04-30T18:30:00.000Z","datatype":"Date","answer":"2023-04-30T18:30:00.000Z"}`
Note the difference in values of valueJSON.answer.

- Looks like observations constructed in server and sent to rules-server for executing messageRule has some issue.

**Comment by 1t5j0y** [comment] 2023-04-18 06:22
Confirmed as fixed by https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/874
Closing as dupe.

**Closed by 1t5j0y** 2023-04-18 06:22 UTC
Labels: bug
