### ISSUE TITLE
Bulk subject migration by sync concepts

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#747] opened 2024-07-09 12:00 UTC
https://avni.freshdesk.com/a/tickets/4290

### Current status:
Currently we are supporting API bulk subject migration only when addresses for subjects need to be updated. 

### AC:
- Support /api/subjectMigration/bulk for syncConcepts also
- When mode query param is  'bySyncConcepts', it is by sync concepts. When mode query param is  'byAddress', it is by address
- The below sample input should migrate all the entities(enrolment, encounter, etc.,) of all the individuals(including individual) returned with ids individualIds, such that users with the updated sync attributes should be able to sync the individuals, and users with old sync attributes should not have the individuals anymore in their mobile device.

```
 /api/subjectMigration/bulk?mode='bySyncConcepts'
{
  individualIds: [uuid1, uuid2, uuid3....uuid_n ]
  syncConceptAttributes: {
        'sync_concept_uuid1': 'value1',
        'sync_concept_uuid2': 'value2',
        'sync_concept_uuid3': 'value3'
   }
}
```
where, 
          - individualIds: array of individual uuids whose individuals need to be migrated
          - sync_concept_uuid1,2,3: uuid of the sync concept to be updated
          - value1,2,3: uuid of the coded concept answer or number or text based on the datatype of sync concept to be updated

- Remove subjectTypeIds parameter in the body for both modes
- In both modes, individualIds body parameter need to be supported.
- Return a callback URL(/api/subjectMigration/status/{id}) where implementors can check the status of migration
    ```
    {
    "message": "Request received. Check status at the callback URL.",
    "callbackUrl": "https://{domainName}/api/subjectMigration/status/{id}"
    }
    ```
- When relevant body parameters are missing for the mode or incorrect body structure or mode return 400. 
- Default mode is 'byAddress'
- In the callback URL, response need to be as below:
      - when not yet completed processing: 
      ```
          {
            "message": "Migration status not yet available. Please check after sometime."  
          }
        ``` 
      - for success response: 
      ```
{
                      "message": "All subjects migrated successfully."
                     }
            ```
      - for partially migrated/not migrated failure response: 
      ```
      {
      "message": "Unable to migrate all the subjects.",
      "notMigratedIndividualIds": [uuid1, uuid2, uuid3....uuid_n ]
      }
      ```
- Update API documentation

### Technical inputs as discussed:
- Make it a batch job with multiple granular transactions
- Add a try catch to keep track of the subjects not migrated.

**Comment by himeshr** [comment] 2024-08-02 13:09
Code review comments added inline with commits.

**Comment by 1t5j0y** [comment] 2024-08-05 06:10
Changes from AC:
- subjects not migrated logged in file and uploaded to s3 for solution to scale
- Reusing common job status response as target users of this API are internal instead of custom response

API:
<details>
<summary>
POST /api/subjectMigration/bulk
</summary>

```
curl --request POST \
  --url 'http://localhost:8021/api/subjectMigration/bulk?mode=bySyncConcept' \
  --header 'AUTH-TOKEN: eyJraWQiOiJlQWdKblRMcnJyNVRKUFB6eGtLbWIzNStFUnFjcllPYmNZam5EdUtoWElvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzZDU5NzA3Yi0xOTBlLTRlMTAtYjE5OC0yODkyYzhkYjFiMWUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmFwLXNvdXRoLTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGgtMV9oV0VPdmpaVUgiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOnRydWUsImNvZ25pdG86dXNlcm5hbWUiOiJqb3lhQHRlc3Rqb3kyIiwiY3VzdG9tOnVzZXJVVUlEIjoiMzIzNTk0NzMtNGMyNS00NzMxLWEzMDUtZTY5MzFkOTg0OTkxIiwiYXVkIjoiN2Ric3JnZzU2bXB0cjR1ZTFnNjVudjNzODYiLCJldmVudF9pZCI6ImU1OTVjMDU3LTdiMDQtNDMxYS1hMDEyLTE4Y2JhZmYyNDRiOCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzIyNTEzNjc0LCJwaG9uZV9udW1iZXIiOiIrOTE5MTY3NTk3OTY3IiwiZXhwIjoxNzIyNTkyMTkyLCJpYXQiOjE3MjI1ODg1OTIsImVtYWlsIjoiam95YUBzYW1hbnZheWZvdW5kYXRpb24ub3JnIn0.SAz0N0WtKbyYtF2ISS74xRclHPdOExhndqMMqPXyI1zX-Ddv0K72VPkwEt_NqlDbuwzA8ceO6jHfY3V9gNFIVzSSu70fxKRlxL9sIlOVBwTE2IPk3q2DP3d5O_zExkEvhZM5PlAu3lv-KUUr0jqEKEB9hoNxyfmOd4RD8S-ygCtL_OmIuObZJOSJxIFp6YCjLGI3Isyupfno3dQpvL6JHbhcSSY_KwO8h0n8AqHZXolvcewJw0ZnHn_IajkgxXerJbQsEJgzX5199ISj7qx2xKfMZXxo0BkaURQrYkDBWVgh-BGkp89EjZuBlwI3J1Rdu8Y5GeDAk3-gPCAEk3j5Sg' \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: insomnia/2023.5.8' \
  --cookie XSRF-TOKEN=839c4903-7cae-440f-9467-bae2b7413899 \
  --data '{
	"destinationAddresses": {
                      "409489": "409480",
                      "409480": "409489"
                  },
	"destinationSyncConcepts": {
		"c87fcab6-104f-41b2-9ff2-e73f9bb76bc5": "3461e18c-7a62-4df5-89b9-45ab7d329605"
	},
	"subjectIds": [
		1331130,
1331127

	]
}'
```

</details>


<details>
<summary>
GET /api/subjectMigration/bulk/status
</summary>

```
curl --request GET \
  --url http://localhost:8021/api/subjectMigration/bulk/status/f9144aad-6c9b-4468-928b-4ff678725115 \
  --header 'AUTH-TOKEN: eyJraWQiOiJlQWdKblRMcnJyNVRKUFB6eGtLbWIzNStFUnFjcllPYmNZam5EdUtoWElvPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiIzZDU5NzA3Yi0xOTBlLTRlMTAtYjE5OC0yODkyYzhkYjFiMWUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLmFwLXNvdXRoLTEuYW1hem9uYXdzLmNvbVwvYXAtc291dGgtMV9oV0VPdmpaVUgiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOnRydWUsImNvZ25pdG86dXNlcm5hbWUiOiJqb3lhQHRlc3Rqb3kyIiwiY3VzdG9tOnVzZXJVVUlEIjoiMzIzNTk0NzMtNGMyNS00NzMxLWEzMDUtZTY5MzFkOTg0OTkxIiwiYXVkIjoiN2Ric3JnZzU2bXB0cjR1ZTFnNjVudjNzODYiLCJldmVudF9pZCI6ImU1OTVjMDU3LTdiMDQtNDMxYS1hMDEyLTE4Y2JhZmYyNDRiOCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNzIyNTEzNjc0LCJwaG9uZV9udW1iZXIiOiIrOTE5MTY3NTk3OTY3IiwiZXhwIjoxNzIyODM1OTc5LCJpYXQiOjE3MjI4MzIzNzksImVtYWlsIjoiam95YUBzYW1hbnZheWZvdW5kYXRpb24ub3JnIn0.VuhlRzNM2m3447llfngPW9fqfskWPg92GC0Hf4EuhI4j21-5DWsGvyM7_4aUUXMe_6gFnJ2W-Z0zHPSm1m5z0Nyxq-aDTGDbOItjWDQqymyfZ9_sDhUzAvHmufc8qZVe6PYVKhPE49XJ4dLe4iI73n59R8qslk_MFbfQZbP0QN6_oayjnG3X7aOnsb6xovzm5TOOxhLtihEKoVSV5OhORPcdPkuvmAvK-kO8xGv5KeFULefwKtKjpPSr13wnEaBgDHYUpQGwFx8ORhDytD09MRDYaRrNosEZRHjaUecI4gxbeshwuqWxBGypbsPFCXRKM9ZtwcHut1Dioh1dz36XkQ' \
  --header 'Content-Type: application/json' \
  --header 'User-Agent: insomnia/2023.5.8' \
  --cookie XSRF-TOKEN=839c4903-7cae-440f-9467-bae2b7413899
```

</details>

**Comment by himeshr** [comment] 2024-08-07 07:53
[BulkSubjectMigrationTestCases.txt](https://github.com/user-attachments/files/16520108/BulkSubjectMigrationTestCases.txt)

**Comment by 1t5j0y** [comment] 2024-08-07 10:29
Fixing issue 1 requires changes to our error interceptors since the failure happens before the controller gets the request since the issue is with parsing the request itself. Since the API docs mention the required format for the subject ids and it is mostly for internal use, I suggest we move forward as-is.

Unable to simulate issue 2.

**Comment by himeshr** [comment] 2024-08-07 10:35
> Fixing issue 1 requires changes to our error interceptors since the failure happens before the controller gets the request since the issue is with parsing the request itself. Since the API docs mention the required format for the subject ids and the API is mostly for internal use, I suggest we move forward as-is.
> 
> Unable to simulate issue 2.

Yup, the second case is not reproduced, should have been due to me using a voided addressLevel as target value.
In general, allowing migration of voided concepts too seems acceptable.

The first case was a general usage experience issue, which seems out of scope for now.
Moving card to done.

**Closed** 2024-08-07 11:10 UTC
