### ISSUE TITLE
Association error - Program enrolment unable to find

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#624] opened 2023-10-09 04:13 UTC
### Bugsnag error link: click [here](https://app.bugsnag.com/samanvay-research-and-development-foundation/avni-client/errors/6482c684187cc200073e7bdb?filters[event.since]=7d&filters[app.release_stage]=prod&filters[error.status]=for_review&filters[search][]=is&filters[search][]=unable&filters[search][]=to&filters[search][]=find&event_id=651fe34d00c59f63418e0000)

ProgramEncounter{uuid='7441027f-30a5-44c9-a2a1-3fab4b62567d'} is unable to find ProgramEnrolment{uuid='69fa8383-f48f-4077-8ed4-53c6a0...

### Steps to reproduce:
Prod env, login id: maha_annapurna@apfodisha, password is our old password

### Analysis:

Current scenario:
- Whenever a ANC encounter is saved, encountter, enrolment and registeration decision observations are updated. And hence their last_modified_date_time are also updated. But for the rows returned by below query, the individual's enrolment last_modified_date_time is not updated. 

```
select * from subject_migration where created_date_time > '2023-06-23'::timestamptz and individual_id in(select individual_id from program_enrolment where last_modified_date_time < '2023-06-22 23:59:59'::timestamptz and last_modified_date_time > '2023-06-22 00:00:00'::timestamptz and program_id=488) and new_sync_concept_1_value='8ebbf088-f292-483e-9084-7de919ce67b7' order by created_date_time desc;
```

It is the above that results in the association error. The ANC encounter decision rule, to update its enrolment decisions was made in the June month itself.

### Acceptance criteria:
Find the reason for why enrolment last_modifiled_date_time is not updated eventhough its decision observations seem to be updated.

**Comment by petmongrels** [comment] 2023-10-09 11:38
busnag error

Error Fatal error: ProgramEncounter{uuid='7441027f-30a5-44c9-a2a1-3fab4b62567d'} is unable to find ProgramEnrolment{uuid='69fa8383-f48f-4077-8ed4-53c6a0d3b90f'} 
    /home/circleci/avni-client/packages/openchs-android/node_modules/openchs-models/dist/error/SyncError.js:10:27 SyncError
    /home/circleci/avni-client/packages/openchs-android/node_modules/openchs-models/dist/BaseEntity.js:127:33 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/openchs-models/dist/ProgramEnrolment.js:229:68 value
    /home/circleci/avni-client/packages/openchs-android/src/service/SyncService.js:262:96 
    [native code] map
    /home/circleci/avni-client/packages/openchs-android/src/service/SyncService.js:262:17 _class2
    /home/circleci/avni-client/packages/openchs-android/src/service/SyncService.js:293:66 _class2
    [native code] value
    /home/circleci/avni-client/packages/openchs-android/src/service/rest/ConventionalRestClient.js:86:28 processResponse
    /home/circleci/avni-client/packages/openchs-android/src/service/rest/ConventionalRestClient.js:94:28 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/node_modules/promise/setimmediate/core.js:37:14 tryCallOne
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/node_modules/promise/setimmediate/core.js:123:25 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:248:17 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:112:6 _callTimer
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:162:15 _callReactNativeMicrotasksPass
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/Core/Timers/JSTimers.js:413:11 callReactNativeMicrotasks
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:391:11 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:133:11 
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:368:8 value
    /home/circleci/avni-client/packages/openchs-android/node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:132:17 value
    [native code] value
    [native code] value

**Comment by petmongrels** [comment] 2023-10-09 16:36
pls check the commit.

#### Problem
in three scenarios we are not updating the audit fields of encounter, individual, enrolment, groupSubject, programEncounter, approval status.
1. when sync attributes get updated during CSV upload
2. when subject migration happens
3. glific entities like message receiver (not relevant from sync perspective)

2 is be a problem for organisations that are using subject migration intentionally as part of their workflow to communicate between different user's work. the problem happens in this way:
- subject migration happens as a consequence of app wizard where user may change location or other fields in Individual.
- the decision rules may update program encounter or enrolment etc
- the entities who fields have been changed will get new lastModifiedDateTime because of hibernate auditing
- the entities whose fields haven't been changed will not get new lastModifiedDateTime because of this bug
- this will create sync problem as is reproducible in this card's scenario

#### Extent of the problem
- it can be assess by looking at the result of the following queries. the idea is that in no-case the subject migration lastModified should be after encounter, individual, enrolment, groupSubject, programEncounter, approval status


`select count(*) from subject_migration
    join individual on subject_migration.individual_id = individual.id
    where extract(epoch from (subject_migration.last_modified_date_time - individual.last_modified_date_time)) > 0 and subject_migration.is_voided = false and individual.is_voided = false;`

`select count(*) from subject_migration
            join individual on subject_migration.individual_id = individual.id
            join program_enrolment on individual.id = program_enrolment.individual_id
            where extract(epoch from (subject_migration.last_modified_date_time - program_enrolment.last_modified_date_time)) > 0 and subject_migration.is_voided = false and individual.is_voided = false and program_enrolment.is_voided = false;`

`select count(*) from subject_migration
     join individual on subject_migration.individual_id = individual.id
     join encounter on individual.id = encounter.individual_id
where extract(epoch from (subject_migration.last_modified_date_time - encounter.last_modified_date_time)) > 0 and subject_migration.is_voided = false and individual.is_voided = false and encounter.is_voided = false`


so on...

**Comment by mahalakshme** [comment] 2023-10-10 03:14
@petmongrels for the scenarios u mentioned from what I understand it will not be an issue for APF odisha:

**Comment by petmongrels** [comment] 2023-10-10 12:14
Prerelease has decent number of records for APF, so will test there and update the timestamps over there.

Work items

Code changes
—————
- remove fetch of subject tree during subject migration on client
- subject migration runs in the same sequence as it is now. It will also be saved t the db like before
- update audit values during subject migration for all entities including the missed out ones like checklist, checklist item, individual relationship

Preparation
——————
- Create a mobile db dump for a QRT user and one non-QRT user

Database update
——————
- update time stamps in db for all entities (individual…….checklist item) linked to subject migration to current timestamp

Testing
————
- test sync performance and correctness without dump
- test sync performance and correctness with dump
- two device testing - update subject by changing location, sync attributes and sync to the other device)

**Comment by vinayvenu** [comment] 2023-10-10 12:20
We need to refresh prerelease db to get some decent number of rows on subject_migration

**Comment by petmongrels** [comment] 2023-10-17 11:28
i. sql is updated for EAS.

**Comment by mahalakshme** [comment] 2023-10-17 12:59
point 1 mentioned above will be moved to separate card since the performance improvement out of it will be less than other valuable cards.

**Comment by AchalaBelokar** [comment] 2023-10-19 08:19
1. sync status is showing up and down percentage see the video you get more idea.

https://github.com/avniproject/avni-server/assets/104890488/5008dbda-b3ca-414e-8171-02974eb488fd
checked with these user maha_annapurna@apfodisha

**Comment by petmongrels** [comment] 2023-10-20 04:42
@AchalaBelokar the first one I couldn't reproduce. Can you try it again and see if it is happening for you.

**Comment by petmongrels** [comment] 2023-10-20 09:48
the second issue is due the decision rule in Individual form in APF.

**Comment by petmongrels** [comment] 2023-10-20 09:59
Not reported in this card, but there was a subject migration issue causing association error that has been fixed now.

**Comment by AchalaBelokar** [comment] 2023-10-20 10:10
@petmongrels 1st issue is not able to reproduce

**Comment by AchalaBelokar** [comment] 2023-10-23 11:14
- [ ] I login with AchalaB@rwbnitiuat and created a work order and sync and after that login with AchalaB@rebnitiuat  on diff mobile work order is not reflected there

**Comment by 1t5j0y** [comment] 2023-10-24 06:20
Facing GroupSubject/Individual association error on fresh sync.
Env: prerelease
User: joyps@apfodisha
```
group_subject uuid = 'ff4b95bd-ff9d-489d-9710-54fc0f6950d6'
individual uuid = '5205e304-c23a-4ef3-8734-e5a93acb04d6'
```
https://github.com/avniproject/avni-server/assets/54208632/05231303-f678-4582-9b43-275337a484b5

**Comment by mahalakshme** [comment] 2023-10-24 08:43
as per vivek: the above is bcoz of incorrect setup of users. Just mentioning here for future reference.

**Closed** 2023-10-25 06:14 UTC

**Comment by mahalakshme** [comment] 2023-10-27 08:57
@petmongrels for this comment: https://github.com/avniproject/avni-server/issues/624#issuecomment-1755260354 I see there is a difference of 45 minutes from current time, when we add program_encounter id which need to be downtime, else might cause association error when syncing, since we sync until 'now'. To prevent that, can we make last_modified data_time of entities same as last_modified_date_time of its subject_migration?

**Comment by petmongrels** [comment] 2023-10-27 09:23
we cannot do that as entities may have been modified without creating new subject migration

**Comment by mahalakshme** [comment] 2023-10-27 10:48
we are doing `subject_migration.individual_id = individual.id` and this `(subject_migration.last_modified_date_time - individual.last_modified_date_time)) > 0` as part of your query. So that will take care of the above right?

**Comment by petmongrels** [comment] 2023-10-27 14:15
The user's timestamp will have moved forward and will be close to now(). We want to ensure that these records are synced again to the user's device so that they do not face any association error - because of non-syncing of some data in the past. So the new timestamp should be more than now.

**Comment by mahalakshme** [comment] 2023-10-30 04:33
@petmongrels so the QRT users are gonna do fresh sync. I dont see POSHAN sathi users will be facing problem since they have both High and Low risk. I am afraid this will increase the sync time unnecessarily after the release. If we make it last_modified_date_time of its subject_migration, sync time will not get affected, and down-time will be less(though our app is an offline app).
