### ISSUE TITLE
POST to create Call task doesn't support PhoneNumber datatype

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-server#557] opened 2023-05-24 12:18 UTC
Steps to reproduce:
- org: PoWERTest, env: staging
- POST to `https://staging.avniproject.org/api/task` with the below body:
`{
  "ID": "string",
  "External ID": "string",
  "Voided": false,
  "Task type": "Call",
  "Task status": "Complete",
  "Name": "Call",
  "Scheduled on": "2022-08-12",
  "Completed on": "2023-05-24",
  "Assigned to": "maha",
  "metadata": {
    "contact": "9791217078"
  },
  "observations": {
    "photo": "https://drive.google.com/uc?export=download&id=1R-IaYnviXH5l2lipuDEj0c9j5Eg9kb6W"
  }
}` where contact is of PhoneNumber datatype.

- When done the above, it returns error response: `Call type task cannot be saved without mobile number. If you have provided the mobile number please contact support.`
- The above should have worked and not returned error response.

**Comment by vinayvenu** [comment] 2023-06-01 04:44
@mahalakshme Any datatype of type "Phone Number" is not considered a contact number. Since this is a task of type "Call", we will need the concept to be marked as such. This looks like working as designed. 

Closing this card.

**Closed by vinayvenu** 2023-06-01 04:44 UTC
Labels: bug
